# Generated by Django 3.2.15 on 2022-10-19 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievements',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='achievements',
            name='image',
            field=models.ImageField(default='../achievement-image_e4ii4f', upload_to='images/'),
        ),
    ]
