# Generated by Django 3.2.15 on 2022-09-20 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do', '0002_auto_20220920_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='urgent',
            field=models.BooleanField(null=True),
        ),
    ]
