# Generated by Django 3.2.15 on 2022-10-19 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do', '0005_todo_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='urgent',
        ),
        migrations.AlterField(
            model_name='todo',
            name='content',
            field=models.TextField(),
        ),
    ]
