# Generated by Django 3.2.15 on 2022-10-20 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('to_do', '0006_auto_20221019_0740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='status',
        ),
    ]
