# Generated by Django 3.2.15 on 2022-09-19 12:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('achievements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AchievementLikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('achievement_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_achievements', to='achievements.achievements')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_on'],
                'unique_together': {('owner', 'achievement_post')},
            },
        ),
    ]
