# Generated by Django 3.2.15 on 2022-10-19 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memo_posts', '0002_rename_for_memo_attention_of'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memo',
            name='content',
            field=models.TextField(),
        ),
    ]
